### ISSUE TITLE
OOB experience is poor/not functional

### ISSUE THREAD

**Issue by pypeaday** [thevinter/cottontail#1]
I'm working on setting this up at home, and I'm a pretty seasoned python developer. I'm not familiar at all with the telegram package though.

So I've forked and setup my venv, and installed the requirements and verified the versions match the file.

1. there is no `main.py`, looks like in README that should be `cottontail.py`
2. It actually doesn't work - I've been battling import errors

## Import errors

`ImportError: cannot import name 'ChatAction' from 'telegram'`

This can fixed with `from telegram.constants import ChatAction`

but then we have `ImportError: cannot import name 'Filters' from 'telegram.ext'`

I see in the telegram repo that `Filters` was deprecated for `filters`, but if I update that then I'm lost on how to fix the `ALLOWED_CHATS` variable since neither `filters.Chat` or `filters.CHAT` worked (I was hoping it'd work just like `Filters.text` -> `filters.TEXT` which does work fine)

I'm using python 3.11.10 and here's the package list for verification

```
❯ uv pip list
Package                 Version
----------------------- -----------
aiohappyeyeballs        2.4.3
aiohttp                 3.10.10
aiosignal               1.3.1
anyio                   4.6.2.post1
asttokens               2.4.1
attrs                   24.2.0
cachetools              5.5.0
certifi                 2024.8.30
charset-normalizer      3.4.0
dataclasses-json        0.5.14
decorator               5.1.1
executing               2.1.0
frozenlist              1.4.1
gptcache                0.1.44
greenlet                3.1.1
h11                     0.14.0
httpcore                0.16.3
httpx                   0.23.3
idna                    3.10
ipython                 8.28.0
jedi                    0.19.1
langchain               0.0.139
marshmallow             3.22.0
matplotlib-inline       0.1.7
multidict               6.1.0
mypy-extensions         1.0.0
numpy                   1.26.4
openai                  0.27.2
openapi-schema-pydantic 1.2.4
packaging               24.1
parso                   0.8.4
pexpect                 4.9.0
prompt-toolkit          3.0.48
propcache               0.2.0
ptyprocess              0.7.0
pure-eval               0.2.3
pydantic                1.10.18
pygments                2.18.0
python-dotenv           1.0.0
python-telegram-bot     20.2
pyyaml                  6.0.2
requests                2.32.3
rfc3986                 1.5.0
six                     1.16.0
sniffio                 1.3.1
sqlalchemy              1.4.54
stack-data              0.6.3
tenacity                8.5.0
tqdm                    4.66.5
traitlets               5.14.3
typing-extensions       4.12.2
typing-inspect          0.9.0
urllib3                 2.2.3
wcwidth                 0.2.13
yarl                    1.15.3
```

**Comment by thevinter** [comment]
Hey, thanks for the issue! I'll admit I haven't looked into this for a while so I assume a lot of dependencies broke and/or got deprecated. I'll take a look in the following days and hopefully update everything to a working state

**Comment by thevinter** [comment]
I didn't have time to fully test it due to a lack of a Google API key but https://github.com/thevinter/cottontail/commit/35669e6713ed29d9990b4f796cde07dcfab654bd should provide a more functional starting point. The bot now works out of the box and receives chat updates. 

I also froze the library versions, so this hopefully won't happen again in the future. 

If you're able to test it please feel free to open issues for anything else you find.
